language: dita
before_install:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in licenseKey.txt.enc -out licenseKey.txt -d
install:
  - echo "Installed"
script:
  - sh .travis/publish.sh
after_success:
  - sh .travis/deploy.sh
env:
  global:
    - DITAMAP=/dita_documenation/create_portfolio/create_portfolio.ditamap
#     - DITAVAL=/path/to/your/ditaval/file
    - ANT_OPTS=-Xmx1024M
