language: xslt
install:
- echo "Installed"
script:
- sh .travis/publish.sh
after_success:
- sh .travis/deploy.sh
env:
  global:
  - TITLE="Intelligent Interactive Styleguide"
  - WELCOME="Your DITA Styleguide"
  - TEMPLATE="oxygen"
  - VARIANT="tiles"
notifications:
  email:
on_success: always
